FROM node:18 AS development
ENV NODE_ENV development
WORKDIR /yfs-app
COPY package*.json ./
COPY yarn.lock .
RUN yarn install
# Copy the rest of the application code to the container
COPY . .
# Build the React app
RUN yarn build
EXPOSE 3000
#start the app
CMD [ "yarn", "start" ]


