version: '3.8'

networks:
  yfs-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24

services:
  backend:
    container_name: YFS-Api-Backend
    build:
      context: .
      dockerfile: Dockerfile.net
    environment:
      - DefaultConnection=Server=YFS-DB-MSSQLExpress;Database=YFS;User Id=SA;Password=1234qweR
    networks:
      yfs-network:
        ipv4_address: 10.10.10.20
    ports:
      - "8080:5001"
    depends_on:
      - database

  database:
    container_name: YFS-DB-MSSQLExpress
    build:
      context: .
      dockerfile: Dockerfile.mssql
    networks:
      yfs-network:
        ipv4_address: 10.10.10.10
    ports:
      - "14330:1433" 
    environment:
      - SA_PASSWORD=1234qweR
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
